image: node:latest

variables:
  BOOKING_WEB_IMAGE_NAME: registry.gitlab.com/tw-catalyst/booking-web/reactapp

stages:
  - test
  - build-integration
  - deploy-integration
  - build-staging
  - deploy-staging
  - build-prod
  - deploy-prod

test:
  stage: test
  artifacts:
    paths:
      - build
  variables:
    CI: "true"
  script:
    - yarn config set cache-folder .yarn
    - yarn install
    - yarn test
    - yarn build
  only:
    - master

build-integration:
  image: docker:latest
  stage: build-integration
  services:
    - docker:dind
  environment:
    name: integration
  script:
    - export REACT_IMAGE=$BOOKING_WEB_IMAGE_NAME:$CI_COMMIT_SHORT_SHA-$CI_ENVIRONMENT_SLUG
    - echo "image info - $REACT_IMAGE"
    - docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com
    - docker build --build-arg ENVIRONMENT=$CI_ENVIRONMENT_SLUG -t $REACT_IMAGE .
    - docker push $REACT_IMAGE
  only:
    - master

deploy-integration:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  stage: deploy-integration
  environment:
    name: integration
  script:
    - cd deploy
    - ./deploy.sh
  only:
    - master

build-staging:
  image: docker:latest
  stage: build-staging
  when: manual
  services:
    - docker:dind
  environment:
    name: staging
  script:
    - export REACT_IMAGE=$BOOKING_WEB_IMAGE_NAME:$CI_COMMIT_SHORT_SHA-$CI_ENVIRONMENT_SLUG
    - echo "image info - $REACT_IMAGE"
    - docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com
    - docker build --build-arg ENVIRONMENT=$CI_ENVIRONMENT_SLUG -t $REACT_IMAGE .
    - docker push $REACT_IMAGE
  only:
    - master

deploy-staging:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  stage: deploy-staging
  when: manual
  environment:
    name: staging
  script:
    - cd deploy
    - ./deploy.sh
  only:
    - master

build-prod:
  image: docker:latest
  stage: build-prod
  when: manual
  services:
    - docker:dind
  environment:
    name: prod
  script:
    - export REACT_IMAGE=$BOOKING_WEB_IMAGE_NAME:$CI_COMMIT_SHORT_SHA-$CI_ENVIRONMENT_SLUG
    - echo "image info - $REACT_IMAGE"
    - docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com
    - docker build --build-arg ENVIRONMENT=$CI_ENVIRONMENT_SLUG -t $REACT_IMAGE .
    - docker push $REACT_IMAGE
  only:
    - master

deploy-prod:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  stage: deploy-prod
  when: manual
  environment:
    name: prod
  script:
    - cd deploy
    - ./deploy.sh
  only:
    - master