version: 0.0
os: linux
files:
  - source: frontend-outputs.sh
    destination: /home/ec2-user/deployment/
permissions:
  - object: /home/ec2-user/deployment/
    pattern: frontend-outputs.sh
    owner: ec2-user
    group: ec2-user
    mode: 500
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user