version: 0.0
os: linux
files:
  - source: outputs.sh
    destination: /home/ec2-user/deployment/frontend/
permissions:
  - object: /home/ec2-user/deployment/frontend
    group: ec2-user
    owner: ec2-user
    type:
      - directory
  - object: /home/ec2-user/deployment/frontend/
    pattern: outputs.sh
    owner: ec2-user
    group: ec2-user
    mode: 500
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user