version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - docker --version
      - CI_COMMIT_SHORT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-6)
      - REACT_IMAGE="$REGISTRY_URI/neev-$BATCH_ID-team-$TEAM_ID-frontend-ecr"
      - echo "building $REACT_IMAGE with tag $CI_COMMIT_SHORT_SHA"
      - $(aws ecr get-login --no-include-email --region $REGION --registry-ids $REGISTRY_ID) # TODO : depricated; find a better way
  build:
    commands:
      - yarn --version
      - node --version
      - yarn config set cache-folder .yarn
      - yarn install
      - yarn test
      - yarn build
      - docker build --build-arg ENVIRONMENT=$CI_ENVIRONMENT_SLUG -t "$REACT_IMAGE:$CI_COMMIT_SHORT_SHA" .
  post_build:
    commands:
      - echo "Pushing $REACT_IMAGE:$CI_COMMIT_SHORT_SHA"
      - docker push "$REACT_IMAGE:$CI_COMMIT_SHORT_SHA"
      - echo "Creating image definitions file"
      - printf '[{"name":"frontend","imageUri":"%s"},' "$REACT_IMAGE:$CI_COMMIT_SHORT_SHA" >> imagedefinitions.json

artifacts:
  files: imagedefinitions.json
